### PR TITLE
Add pt_BR lang

### PR DESCRIPTION
**Pull request by vectorwing**
Heyo. Got a lang for ya!

A few notes I'd like to discuss first. If you're OK with the current ones, feel free to merge:
- **Meringue:** There are two words for it: _Suspiro_ and _Merengue_. I opted for _Suspiro_ for being the more widespread name across Brazil, though it's somewhat nickname-sounding. Both are valid names, but I wanna hear what you think;
- **Peppermint:** Neapolitan's pt_BR still lacks mint translations, so I went with the usual name here (_Hortelã_). Might change depending on what their translators do about it;
- **Peppermint Bark:** We don't have a direct translation, but given it uses Tree Bark, I called it _"Casca de hortelã"_;
- **Fizzy Yogurt:** Felt weird translating as gaseous/carbonated, so I went with "effervescent". Does it make sense?
- **Maple Bacon:** Literally, the name would be super long: _"Doce de bacon com xarope de bordo"_. I opted to just call it Caramel Bacon" (_Bacon caramelado_). Which do you prefer?

### CODE REVIEW

**Comment by davidjjung** [comment]
Thanks for the lang! Definitely had to take all of your points into consideration--ultimately I think they work great as a whole.

I don't disagree with implementing "suspiro"--Wikipedia page references both, there are receitas for both online, etc, so I think whatever gels more with the youth(tm) should be good

I also understand the weirdness of trying to translate fizzy yogurt, given how off-putting it is in English to begin with. "efervescente" should work just fine though!

surprised neapolitan's pt_br isn't up to date considering how much of the (vocal?) mc fanbase is Brazilian. interestingly, most of the Portuguese (not explicitly Brazilian) references to mint bark i can find online adhere strictly to *pepper*mint bark, so they make it "casca de hortelã-pimento". Maybe that would be preferable? Up to your discretion

Regarding the fudge, I briefly considered if "xaroposo" might fit better--"meloso" seemingly refers slightly more to emotional sweetness in the Portuguese media I could find. However, after reading it over aloud a couple times, I do agree that meloso simply sounds better, haha--there must/may be a specific Brazilian context I'm missing that makes it work here. Though doing some research I went down a bit of a rabbit hole looking for references to "melosa" as a South American herb that only shows up in dictionary definitions, leading me to suspect whether it actually exists outside of that circular internet chamber, or they're just talking about lemon balm 🙉 but I digress

thanks again for the contribution! I'll merge as soon as we come to a verdict on the bark. Take care!

**Comment by vectorwing** [comment]
> surprised neapolitan's pt_br isn't up to date considering how much of the (vocal?) mc fanbase is Brazilian. interestingly, most of the Portuguese (not explicitly Brazilian) references to mint bark i can find online adhere strictly to peppermint bark, so they make it "casca de hortelã-pimento". Maybe that would be preferable? Up to your discretion

_Hortelã-pimenta_ isn't commonly used in popular speech, but it is also correct (and used for some recipes). Since there are no direct translations to this candy (which is apparently chocolate sprinkled with peppermint cane bits), it could be one of either:

- "Casca de bala de hortelã" - Roughly "peppermint candy bark", to mention the candy part;
- "Casca de hortelã-pimenta" - The rare, but existing translation of the candy in brazilian recipe websites;
- "Casca de hortelã" - The shorter form.

> Regarding the fudge, I briefly considered if "xaroposo" might fit better--"meloso" seemingly refers slightly more to emotional sweetness in the Portuguese media I could find. [...]

Hmm, nether of those terms are precise for the item, I feel. _"Xaroposo"_ means something that is syrupy, not glazed.
I searched some more and a nicer term is _"caramelizado"_. We don't usually denote what the glaze is made of, but it could be added in. Something like _"Bacon caramelizado ao bordo"_.

**Comment by davidjjung** [comment]
Brevity is nice, so definitely casting my vote for "Casca de hortelã" if deemed acceptable, haha.

After re-evaluating at a more human level of coherence, I agree that none of the things I proposed really fit the bill--"caramelizado" conjures up a lot more crystallized/solid-feeling imagery, which is quite good. I don't think stating the contents of the glaze will really be necessary given that the player understands its ingredients, so I'm down for your proposed solutions.

**Comment by vectorwing** [comment]
Alright! I tweaked up Maple Bacon Fudge, and left the other lang as is. 👍

**Pull request merged**
